openapi: 3.0.1
info:
  contact:
    email: lampralexandros@gmail.com
  description: This is a sample openApi document
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://wabli.netlify.app/
  title: TempApi
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- description: local-host
  url: http://localhost:8090/v1
security:
- {}
tags:
- description: not yet ready
  name: post
paths:
  /post:
    post:
      operationId: createpost
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/post'
        description: data to be created
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/post'
          description: successful operation
      summary: Creates the data
      tags:
      - post
      x-eov-operation-handler: controllers/PostController
  /post/{postId}:
    delete:
      operationId: deletepost
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: postId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: successful operation
      summary: Delete the element
      tags:
      - post
      x-eov-operation-handler: controllers/PostController
    get:
      operationId: getpost
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: postId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/post'
          description: successful operation
      summary: Get the element
      tags:
      - post
      x-eov-operation-handler: controllers/PostController
    put:
      operationId: updatepost
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: postId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/post'
        description: data to be updated
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/post'
          description: successful operation
      summary: Updates the element
      tags:
      - post
      x-eov-operation-handler: controllers/PostController
  /post/getAll:
    get:
      operationId: getAllpost
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/post'
                type: array
          description: successful operation
      summary: Get all the data
      tags:
      - post
      x-method-getAll: "true"
      x-eov-operation-handler: controllers/PostController
components:
  schemas:
    post:
      example:
        sdate: 2000-01-23
        pimage:
          data: data
          name: name
        ptitle: ptitle
        _id: _id
        ptext: ptext
      properties:
        _id:
          type: string
        sdate:
          format: date
          type: string
        pimage:
          $ref: '#/components/schemas/post_pimage'
        ptext:
          type: string
        ptitle:
          type: string
      required:
      - pimage
      - ptext
      - ptitle
      - sdate
      type: object
    post_pimage:
      example:
        data: data
        name: name
      properties:
        data:
          type: string
        name:
          type: string
      type: object
      x-isSchemaOnly: "true"
